version: '3.9'

services:
  app:
    image: ${IMAGE_NAME}
    container_name: housing-ml-api
    ports:
      - "8000:8000"
    environment:
      - ENV=staging
    healthcheck:
      # Lệnh kiểm tra sức khỏe bằng cách gửi yêu cầu GET đến endpoint /health
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5  # Tăng số lần thử lại để đảm bảo ứng dụng có đủ thời gian khởi động