version: '3.9'

services:
  app:
    image: ${IMAGE_NAME}
    container_name: housing-ml-api
    ports:
      - "8000:8000"
    environment:
      - ENV=staging
    healthcheck:
      # Lệnh kiểm tra sức khỏe bằng cách chạy tệp healthcheck.py
      test: ["CMD-SHELL", "python healthcheck.py"]
      interval: 10s
      timeout: 5s
      retries: 5